[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bolt = "GetPeJuUn9dabeSR98haGpQJEYdvvznQYD8yBuXwca7d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zihao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
