[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tale_of_kentridge = "AmXU1Tm8SYYoAwjZwC9hC8wuJWguPYKBD48GurvYyBfe"

[programs.devnet]
tale_of_kentridge = "AmXU1Tm8SYYoAwjZwC9hC8wuJWguPYKBD48GurvYyBfe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/huCDT74XQJEq2Ed1AF8e1lDisWJulLHV"
wallet = "/Users/zihao/phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
